import Head from 'next/head';
import{BsFillMoonStarsFill} from 'react-icons/bs';
import{AiFillTwitterCircle, AiFillLinkedin,AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
export default function Home() {
  return (
    <div >
      <Head>
        <title>Tahmidul Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
      <section className=" min-h-screen">
      <nav className='py-10 mb-12 flex justify-between'>
      <h1 className='text-xl font-burtons'>
        My Portfolio 
      </h1>
      <ul className='flex items-centen'>
        <li>
        <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
        </li>
        <li>
        <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a>
        </li>
      </ul>
      </nav>
      <div className='text-center p-10'>
        <h2 className='text-5xl py-2 text-teal-600 font-medium'> MD Monjurul Hoque</h2>
        <h3 className='text-2xl py-2'>Production Manager</h3>
        <p className='text-md py-5 leading-8 text-gray-800'>
           I am working in the Nanoform last one years. i am 32 years old. i came from bangladesh. i complete my Bsc from Hagiya Heliya University. 
        </p>
      </div>
      <div className='text-4xl flex justify-center gap-16 py-3 text-gray-600'>
        <AiFillLinkedin/>
        <AiFillTwitterCircle/>
        <AiFillYoutube/>
      </div>
      <div className='ralative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden'>
        <Image src={deved} />
      </div>
      </section>
      

      <section>
        <div>
          <h3 className='text-3xl py-1'>Experience</h3>
          <p className='text-md py-2 leading-8 text-gray-800'>
            i have work in microsoft as a logistic operato. i was working in there almost one year. it was a great experience and it was a friendly envirionment.
          </p>
        </div>
      </section>


      </main>
    </div>
  )
}
